version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data